baseurl = "https://lnhutnam.github.io"
title = "lnnam"
theme = "hugo-theme-console"
languageCode = "en-us"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 5
    ordered = false

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  [[params.navlinks]]
  name = "~/about/"
  url = "about/"

  [[params.navlinks]]
  name = "~/posts/"
  url = "posts/"

  [[params.navlinks]]
  name = "~/research/"
  url = "research/"

  [[params.navlinks]]
  name = "~/teaching/"
  url = "teaching/"